test:
    type:     rest
    resource: Api\Bundle\Controller\TestController
 
result:
    type:     rest
    resource: Api\Bundle\Controller\ResultController
 
word:
    type:     rest
    resource: Api\Bundle\Controller\WordController
 
dictionary:
    type:     rest
    resource: Api\Bundle\Controller\DictionaryController
 
user:
    type:     rest
    resource: Api\Bundle\Controller\UserController