<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DictionaryScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getArray(User $u)
    {
        $d = $u->getDefaultDictionary();

        $score = $this
            ->getEntityManager()->getRepository('AppBundle:Result')->getAvgScore($u);

        return array('id' => $u->getId(), 'score' => $score, 'dic' => $d->getJsonArray());
    }
}
