sbk_cron:
    tasks:
        updateNewWord:
            command:    'pebidi:updateNewWord >> /var/www/vhosts/pebidi/app/log/updateNewWord.txt'
            expression: '* * * * *'
        updateJson:
            command:    'pebidi:json >> /var/www/vhosts/pebidi/app/log/json.txt'
            expression: '30 * * * *'

