api:
    type:     rest
    resource: Main\DefaultBundle\Controller\ApiUserController

apiWord:
    type:     rest
    resource: Main\DefaultBundle\Controller\ApiWordController

apiGroupWord:
    type:     rest
    resource: Main\DefaultBundle\Controller\ApiGroupWordController

apiTest:
    type:     rest
    resource: Main\DefaultBundle\Controller\ApiTestController


main_default:
    resource: "@MainDefaultBundle/Controller/"
    type:     annotation
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile