
services:
    app.result_controller:
        class:     AppBundle\Controller\ResultController
    app.word_controller:
        class:     AppBundle\Controller\WordController
        arguments: ["@doctrine.orm.default_entity_manager"]
        
    app.wr_suck:
        class:     AppBundle\DataFixtures\WrSuck
    mailer_manager:
        class:     AppBundle\Mailer\Manager
        arguments: ["@mailer", "@templating"]
