
services:
    app.result_controller:
        class:     AppBundle\Controller\ResultController
    app.word_model:
        class:     AppBundle\Model\WordModel
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.dictionary_model:
        class:     AppBundle\Model\DictionaryModel
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.dictionary_word_model:
        class:     AppBundle\Model\DictionaryWordModel
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.user_model:
        class:     AppBundle\Model\UserModel
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
        
    app.suck_model:
        class:     AppBundle\Model\SuckModel
    mailer_manager:
        class:     AppBundle\Mailer\Manager
        arguments: ["@mailer", "@templating"]
