<?php

namespace Main\DefaultBundle\Repository;

/**
 * DictionaryScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
