<?php

namespace Main\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Main\DefaultBundle\Entity\User;

/**
 * DictionaryScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
    public function getAvgScore(User $u)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('AVG(r.score) as score')
            ->where('r.user = :uid')
            ->setParameter('uid', $u);
        $r = $qb->getQuery()->getOneOrNullResult();
      
        if(!isset($r['score'])) {
          return 0;
        }

        return $r['score'];
    }
}
