<?php

namespace Main\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{

    public function getWordsForTest($nb, $d, $u) {
        $a =  array(
            'did' => $d->getId(),
            'uid' => $u,
        );
        $qb = $this->createQueryBuilder('w')
            ->select('w.id, w.word, t.translation')
            ->addSelect('SUM(p.point)/COUNT(p.id) AS stat_sum_realised')
            ->addSelect('GROUP_CONCAT(DISTINCT def.definition) AS definitions')
            ->leftJoin('w.translations', 't')
            ->leftJoin('w.definitions', 'def')
            ->innerJoin('w.dictionaries', 'd')
            ->leftJoin('w.points','p')
            ->where('d.id = :did')
            ->andWhere('d.user = :uid')
            ->groupBy('w.id')
            ->setParameters($a)
            ->setMaxResults($nb)
            ->orderBy('stat_sum_realised', 'ASC')
        ;

        return $qb->getQuery()->getResult();
    }
}
