parameters:
#    main_default.example.class: Main\DefaultBundle\Example

services:
  persist:
    class: Main\DefaultBundle\Service\PersistService
    arguments: [ "@doctrine.orm.entity_manager" ]
  cookie:
    class: Main\DefaultBundle\Service\CookieService
    arguments: ["@request_stack"]
